language: python
python:
  - "3.6"

sudo: false

branches:
  only:
  - master

services:
  - postgresql

install:
  - sudo apt-get update; sudo apt-get install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev python3 python3-dev libpq-dev postgresql postgresql-contrib nginx
  - sudo pip install pipenv
  - python3 -m venv venv
  - . venv/bin/activate
  - pipenv install

script:
  - bundle exec rake

cache: pip
