version: 2
jobs:
  build:
    working_directory: ~/webscrapingtool
    docker:
      - image: circleci/python:3.5

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo apt-get update; sudo apt-get install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev python3 python3-dev
      - run:
          command: |
            virtualenv -p /usr/bin/python  --system-site-packages venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd webscrapingtool; python manage.py test; cd ..
      - store_artifacts:
          path: test-reports/
          destination: tr1

