# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-20 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
