# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20171220_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_page',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
