# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-21 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20171220_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
