# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-21 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
