# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-21 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
